name: Demo
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get IP of runner
        run: curl https://api.ipify.org
      - name: Setup sonarqube instance
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      	  SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
